-- MySQL Script generated by MySQL Workbench
-- 01/21/16 13:33:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ds_pizzaParlor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ds_pizzaParlor` ;

-- -----------------------------------------------------
-- Schema ds_pizzaParlor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ds_pizzaParlor` DEFAULT CHARACTER SET utf8 ;
USE `ds_pizzaParlor` ;

-- -----------------------------------------------------
-- Table `ds_pizzaParlor`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ds_pizzaParlor`.`customers` ;

CREATE TABLE IF NOT EXISTS `ds_pizzaParlor`.`customers` (
  `custID` INT NOT NULL AUTO_INCREMENT,
  `custFName` VARCHAR(30) NOT NULL,
  `custLName` VARCHAR(30) NOT NULL,
  `custAddress` VARCHAR(30) NOT NULL,
  `custCity` VARCHAR(30) NOT NULL,
  `custState` VARCHAR(30) NOT NULL,
  `custZip` VARCHAR(10) NOT NULL,
  `custPhone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`custID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds_pizzaParlor`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ds_pizzaParlor`.`orders` ;

CREATE TABLE IF NOT EXISTS `ds_pizzaParlor`.`orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `dateTimePlaced` DATE NOT NULL,
  `custID` INT NOT NULL,
  `pizzaDesc` VARCHAR(255) NOT NULL,
  `priceSub` FLOAT NOT NULL,
  `tax` FLOAT NOT NULL,
  `priceTotal` FLOAT NOT NULL,
  `completed` VARCHAR(1) NOT NULL DEFAULT 'n',
  PRIMARY KEY (`orderID`),
  CONSTRAINT `custID_FK`
    FOREIGN KEY (`custID`)
    REFERENCES `ds_pizzaParlor`.`customers` (`custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `custID_FK_idx` ON `ds_pizzaParlor`.`orders` (`custID` ASC);


-- -----------------------------------------------------
-- Table `ds_pizzaParlor`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ds_pizzaParlor`.`admins` ;

CREATE TABLE IF NOT EXISTS `ds_pizzaParlor`.`admins` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `firstName` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(25) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `adminLevel` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;

INSERT INTO `admins` VALUES('0', 'admin', 'Default', 'Default', 'Noth1ng$', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
